# Generated by Django 3.2.19 on 2023-11-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pinogy_form_builder_emailfieldpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('placeholder_text', models.CharField(blank=True, help_text='Default text in a form. Disappears when the user starts typing. Example: "email@example.com"', max_length=255, null=True, verbose_name='Placeholder Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FormPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pinogy_form_builder_formpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('form_name', models.CharField(max_length=255, verbose_name='Form Name')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NumberFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pinogy_form_builder_numberfieldpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('placeholder_text', models.CharField(blank=True, help_text='Default text in a form. Disappears when the user starts typing. Example: "email@example.com"', max_length=255, null=True, verbose_name='Placeholder Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TextAreaFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pinogy_form_builder_textareafieldpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('placeholder_text', models.CharField(blank=True, help_text='Default text in a form. Disappears when the user starts typing. Example: "email@example.com"', max_length=255, null=True, verbose_name='Placeholder Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TextFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pinogy_form_builder_textfieldpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('placeholder_text', models.CharField(blank=True, help_text='Default text in a form. Disappears when the user starts typing. Example: "email@example.com"', max_length=255, null=True, verbose_name='Placeholder Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
