# Generated by Django 3.2.19 on 2023-12-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinogy_form_builder', '0002_checkboxfieldpluginmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkboxfieldpluginmodel',
            name='placeholder_text',
        ),
    ]
