# Generated by Django 3.2.19 on 2023-12-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinogy_form_builder', '0004_locationfieldpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationfieldpluginmodel',
            name='chosen_location',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True, verbose_name='Default Location'),
        ),
    ]
