# Generated by Django 3.2.19 on 2023-12-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinogy_form_builder', '0005_locationfieldpluginmodel_chosen_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationfieldpluginmodel',
            name='chosen_location',
        ),
    ]
