# Generated by Django 3.2.19 on 2023-12-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinogy_form_builder', '0006_remove_locationfieldpluginmodel_chosen_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxfieldpluginmodel',
            name='default',
            field=models.BooleanField(default=False, help_text='Check this box to have the checkbox pre-checked by default', verbose_name='Default'),
        ),
    ]
