# Generated by Django 3.2.19 on 2024-01-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('pinogy_form_builder', '0007_checkboxfieldpluginmodel_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pinogy_form_builder_marketingfieldpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
                ('default_location', models.IntegerField(blank=True, help_text='The marketing location selected from the list', null=True, verbose_name='Selected Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
