# Generated by Django 3.2.19 on 2024-04-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinogy_form_builder', '0009_datetimefieldpluginmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetimefieldpluginmodel',
            name='placeholder_text',
        ),
    ]
