# Generated by Django 3.2.19 on 2024-05-09 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('pinogy_form_builder', '0010_remove_datetimefieldpluginmodel_placeholder_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberFieldPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pinogy_form_builder_phonenumberfieldpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Used to set the field name', max_length=255)),
                ('placeholder_text', models.CharField(blank=True, help_text='Default text in a form. Disappears when the user starts typing. Example: "email@example.com"', max_length=255, null=True, verbose_name='Placeholder Text')),
                ('is_required', models.BooleanField(default=False, verbose_name='Field is required')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
