# Generated by Django 3.1.14 on 2022-08-23 10:59

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='themeimages', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg', 'webp'])])),
                ('image_type', models.CharField(blank=True, choices=[('logo', 'Logo'), ('favicon', 'Favicon')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', colorfield.fields.ColorField(default='#003F5A', image_field=None, max_length=18, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#12BBD2', image_field=None, max_length=18, samples=None)),
                ('heading_font', models.CharField(choices=[('"Open Sans", Arial, sans-serif', 'Open Sans'), ('"Poppins", sans-serif', 'Poppins')], default='"Open Sans", Arial, sans-serif', max_length=100)),
                ('heading_font_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=[('#FFFFFF', 'White'), ('#000000', 'Black')])),
                ('general_font', models.CharField(choices=[('"Open Sans", Arial, sans-serif', 'Open Sans'), ('"Poppins", sans-serif', 'Poppins')], default='"Open Sans", Arial, sans-serif', max_length=100)),
                ('general_font_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=[('#FFFFFF', 'White'), ('#000000', 'Black')])),
                ('primary_button_shape', models.CharField(choices=[('rectangle', 'Rectangle'), ('rounded', 'Rounded corners'), ('pill', 'Pill')], default='rectangle', max_length=100)),
                ('primary_button_style', models.CharField(choices=[('fill', 'Fill'), ('outline', 'Outline')], default='fill', max_length=100)),
                ('primary_button_color_pattern', models.CharField(choices=[('F1', 'Fill primary color with white text'), ('F2', 'Fill secondary color with white text'), ('F3', 'Fill white color with primary color text'), ('F4', 'Fill white color with secondary color text'), ('O1', 'Outline and text primary color'), ('O2', 'Outline and text secondary color'), ('O3', 'Outline and text black color'), ('O4', 'Outline and text white color')], default='F1', max_length=100)),
                ('secondary_button_style', models.CharField(choices=[('fill', 'Fill'), ('outline', 'Outline')], default='outline', max_length=100)),
                ('secondary_button_color_pattern', models.CharField(choices=[('F1', 'Fill primary color with white text'), ('F2', 'Fill secondary color with white text'), ('F3', 'Fill white color with primary color text'), ('F4', 'Fill white color with secondary color text'), ('O1', 'Outline and text primary color'), ('O2', 'Outline and text secondary color'), ('O3', 'Outline and text black color'), ('O4', 'Outline and text white color')], default='O1', max_length=100)),
                ('selected_favicon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_favicon', to='custom_design.themeimages')),
                ('selected_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_logo', to='custom_design.themeimages')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
