# Generated by Django 3.1.14 on 2022-08-24 07:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeconfiguration',
            name='general_font_color',
            field=colorfield.fields.ColorField(default='#000000FF', image_field=None, max_length=18, samples=[('#FFFFFF', 'White'), ('#000000', 'Black')]),
        ),
        migrations.AlterField(
            model_name='themeconfiguration',
            name='heading_font_color',
            field=colorfield.fields.ColorField(default='#000000FF', image_field=None, max_length=18, samples=[('#FFFFFF', 'White'), ('#000000', 'Black')]),
        ),
        migrations.AlterField(
            model_name='themeconfiguration',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#003F5AFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='themeconfiguration',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#12BBD2FF', image_field=None, max_length=18, samples=None),
        ),
    ]
