# Generated by Django 3.1.14 on 2022-08-25 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0002_auto_20220824_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeconfiguration',
            name='selected_favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_favicon', to='custom_design.themeimages'),
        ),
        migrations.AlterField(
            model_name='themeconfiguration',
            name='selected_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_logo', to='custom_design.themeimages'),
        ),
    ]
