# Generated by Django 3.1.14 on 2022-08-30 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0003_auto_20220825_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeimages',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='themeimages', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
    ]
