# Generated by Django 3.1.14 on 2022-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_design", "0004_auto_20220830_1208"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_template",
                    models.CharField(
                        choices=[
                            ("template1", "Template1"),
                            ("template2", "Template2"),
                        ],
                        default="template1",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
