# Generated by Django 3.1.14 on 2022-09-21 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_design", "0005_templateconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateconfig",
            name="template_json",
            field=models.FileField(
                blank=True,
                default=None,
                help_text='<br/><b>Download sample_template.json file </b><a href="/static/json/sample_template.json" download="sample_template.json">Click here</a>',
                null=True,
                upload_to="pagejson",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["json"]
                    )
                ],
            ),
        ),
    ]
