# Generated by Django 3.1.14 on 2022-09-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0006_templateconfig_template_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfiguration',
            name='file_version',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
