# Generated by Django 3.1.14 on 2022-09-23 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0007_themeconfiguration_file_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfiguration',
            name='theme_json',
            field=models.FileField(blank=True, default=None, help_text='<br/><b>Download sample_theme.json file </b><a href="/static/json/sample_theme.json" download="sample_theme.json">Click here</a>', null=True, upload_to='themejson', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
