# Generated by Django 3.1.14 on 2022-11-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0008_themeconfiguration_theme_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeconfiguration',
            name='general_font',
            field=models.CharField(choices=[("'Open Sans', Arial, sans-serif", 'Open Sans'), ("'Poppins', sans-serif", 'Poppins')], default='"Open Sans", Arial, sans-serif', max_length=100),
        ),
        migrations.AlterField(
            model_name='themeconfiguration',
            name='heading_font',
            field=models.CharField(choices=[("'Open Sans', Arial, sans-serif", 'Open Sans'), ("'Poppins', sans-serif", 'Poppins')], default='"Open Sans", Arial, sans-serif', max_length=100),
        ),
    ]
