# Generated by Django 3.1.14 on 2023-04-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0010_auto_20230418_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfiguration',
            name='image_radius',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='themeconfiguration',
            name='image_shape',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('rounded', 'Rounded corners'), ('pill', 'Pill')], default='rectangle', max_length=100),
        ),
    ]
