# Generated by Django 3.2.19 on 2023-07-25 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0012_auto_20230424_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfiguration',
            name='selected_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_background', to='custom_design.themeimages'),
        ),
        migrations.AlterField(
            model_name='themeimages',
            name='image_type',
            field=models.CharField(blank=True, choices=[('logo', 'Logo'), ('favicon', 'Favicon'), ('background', 'Background')], max_length=30),
        ),
    ]
