# Generated by Django 3.2.19 on 2023-10-12 06:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0013_auto_20230725_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfiguration',
            name='alert_color',
            field=colorfield.fields.ColorField(default='#A40000FF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='themeconfiguration',
            name='highlight_color',
            field=colorfield.fields.ColorField(default='#EB8207FF', image_field=None, max_length=18, samples=None),
        ),
    ]
