# Generated by Django 3.2.19 on 2023-10-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0014_auto_20231012_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themeconfiguration',
            name='general_font_color',
        ),
        migrations.RemoveField(
            model_name='themeconfiguration',
            name='heading_font_color',
        ),
    ]
