# Generated by Django 3.2.19 on 2023-10-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0015_auto_20231012_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfiguration',
            name='font_alignment',
            field=models.CharField(default='left', max_length=10),
        ),
    ]
