# Generated by Django 3.2.19 on 2023-10-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0016_themeconfiguration_font_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeconfiguration',
            name='font_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='left', max_length=10),
        ),
    ]
