apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: SITENUM
  namespace: websites-v2
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 120
        type: Pods
        value: 1
      selectPolicy: Max
      stabilizationWindowSeconds: 1200
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 600
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: SITENUM