# Generated by Django 3.2.19 on 2024-02-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinogy_pet', '0002_apipetbadgephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPetAdCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField(blank=True, default=None, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('file_name', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('file_extension', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='file_extension')),
                ('file_image', models.ImageField(upload_to='ap_media')),
                ('file_id', models.IntegerField(blank=True, default=0, verbose_name='remote file ID')),
                ('alt', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('width', models.IntegerField(blank=True, default=0, verbose_name='Image file width')),
                ('height', models.IntegerField(blank=True, default=0, verbose_name='Image file height')),
                ('order_updated_at', models.DateTimeField(auto_now_add=True)),
                ('file_content', models.FileField(upload_to='ap_media')),
                ('file_type', models.CharField(choices=[(0, 'Photo'), (1, 'Video')], default=0, max_length=255)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
