# Generated by Django 3.2.19 on 2024-10-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinogy_pet', '0006_petlistpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='apipetadcard',
            name='ad_card_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='petlistpluginmodel',
            name='button_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
