# Generated by Django 3.1.14 on 2022-10-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('carousel_plugins', '0002_carouselpluginmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetCarouselPluginModel',
        ),
    ]
