# Generated by Django 3.1.14 on 2023-06-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_plugins', '0005_promotionimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionimage',
            old_name='promotion_image_id',
            new_name='file_id',
        ),
    ]
