# Generated by Django 3.2.19 on 2024-10-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_plugins', '0007_gridpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridpluginmodel',
            name='grid_breeds_list',
            field=models.JSONField(default=list),
        ),
    ]
