# Generated by Django 3.2.19 on 2024-10-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_plugins', '0008_gridpluginmodel_grid_breeds_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridpluginmodel',
            name='grid_button_data',
            field=models.JSONField(default=dict),
        ),
    ]
