# Generated by Django 3.1.14 on 2022-10-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoApiSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='', max_length=255, verbose_name='token')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
