# Generated by Django 3.1.14 on 2023-04-12 12:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0002_apipetphoto'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='apipetphoto',
            managers=[
                ('image_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
