# Generated by Django 3.2.19 on 2023-09-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_block', models.TextField(blank=True, default='', help_text='This will be added to header block.')),
                ('body_top_block', models.TextField(blank=True, default='', help_text='This will be added to top of the body block.')),
                ('body_bottom_block', models.TextField(blank=True, default='', help_text='This will be added to bottom of the body block.')),
            ],
            options={
                'verbose_name': 'site configuration',
                'verbose_name_plural': 'site configuration',
            },
        ),
    ]
