apiVersion: v1
data:
  API_LAYWAY: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  CLIENT_ID: MTA3
  DEBUG: ""
  DEFAULT_FROM_EMAIL: bm9yZXBseUBwaW5vZ3kud2Vic2l0ZQ==
  DJANGO_EXTRA_APPS: cGlub2d5X2F2YWlsYWJsZV9wZXRzLHBpbm9neV9sb2NhdGlvbnMscGlub2d5X2NhcmRjb25uZWN0X2lmcmFtZV90b2tlbml6ZXI=
  DJANGO_SETTINGS_MODULE: cGlub2d5X2FwcC5zZXR0aW5ncy5wcm9kdWN0aW9u
  EMAIL_HOST: c210cC5zZW5kZ3JpZC5jb20=
  EMAIL_HOST_PASSWORD: U0cuZmtZZ1NrUUxRTDZUU3JrR1lxNV82US5WYTVIS2syQWxNWUpuVzRQcnVQZUNzNXJrMGRRVWFjUFRfa29LSXlPM3hN
  EMAIL_HOST_USER: YXBpa2V5
  EMAIL_PORT: NTg5
  ENVIRONMENT: UFJPRFVDVElPTg==
  HOST_LIST: Ilt3ZWJzaXRlMDExNy5waW5vZ3kuZGV2XSIK
  IMAGE_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
  INTEGRATION_ID: MTM2
  PINOGY_ACCESS_KEY: TktQR1A2VzhUZFBGN05CV1RiVmo=
  PINOGY_API_HOST: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  PINOGY_API_PASS: MjAyMy0wMi0wNzEyOjE2OjA4MTc5
  PINOGY_SECRET_KEY: UkJReHQ2czY5aGdYeHZTTDIzUGM=
  POSTGRES_DB: d3MwMTE3
  POSTGRES_HOST: MTAuNzMuMC4zOQ==
  POSTGRES_PASSWORD: ODdiYzliMDY4MTg4MmRjYWJjOTZhMTg5MjJmZjQ2OGZkOTc4MjQ0MWNmNWRkYmE0MTg1ODJjMThlYmJiZDU5MA==
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: d3NtYXN0ZXIwMTE3
  RECAPTCHA_PRIVATE_KEY: NkxjOW9mc2lBQUFBQUdLb0J1QlJ5c3lSVEFUNlQ1VkdWVDFXYi1KTA==
  RECAPTCHA_PUBLIC_KEY: NkxjOW9mc2lBQUFBQVBHbnEwNnBHTHhZaTI3NENPV3pfNVdLR3FZbg==
  REDIS_PREFIX: d3MwMTE3
  REDIS_SERVICE: cmVkaXM6Ly9yZWRpczo2Mzc5
  STATIC_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
kind: Secret
metadata:
  name: website0117-secret
  namespace: websites-v2
type: Opaque