apiVersion: v1
data:
  API_LAYWAY: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  DEBUG: ""
  DEFAULT_FROM_EMAIL: bm9yZXBseUBwaW5vZ3kud2Vic2l0ZQ==
  DJANGO_EXTRA_APPS: cGlub2d5X2F2YWlsYWJsZV9wZXRzLHBpbm9neV9sb2NhdGlvbnMscGlub2d5X2NhcmRjb25uZWN0X2lmcmFtZV90b2tlbml6ZXI=
  DJANGO_SETTINGS_MODULE: Y2xpZW50LnNldHRpbmdzLnByb2Q=
  EMAIL_HOST: c210cC5zZW5kZ3JpZC5jb20=
  EMAIL_HOST_PASSWORD: U0cuZmtZZ1NrUUxRTDZUU3JrR1lxNV82US5WYTVIS2syQWxNWUpuVzRQcnVQZUNzNXJrMGRRVWFjUFRfa29LSXlPM3hN
  EMAIL_HOST_USER: YXBpa2V5
  EMAIL_PORT: NTg5
  ENVIRONMENT: UFJPRFVDVElPTg==
  HOST_LIST: Ilt3ZWJzaXRlMDEyMy5waW5vZ3kuZGV2XSIK
  IMAGE_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
  PINOGY_ACCESS_KEY: czZnNktKOUJOWERiUmhKTnBMVkc=
  PINOGY_API_HOST: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  PINOGY_API_PASS: MjAyMy0wMy0zMDE2OjE0OjQ2NQ==
  PINOGY_SECRET_KEY: M0RiUWg3Z3ROQ25zTHNmenBQUlE=
  POSTGRES_DB: d3MwMTIz
  POSTGRES_HOST: MTAuNzMuMC4zOQ==
  POSTGRES_PASSWORD: Mzg1YjQ5YjhlYmNiNzAyY2ZhYzJiMjExMDUzYTg4NTFkMTkwMDViNDJmYTQxODdkNjRkZjk2YWZmYzE5NjMwMw==
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: d3NtYXN0ZXIwMTIz
  RECAPTCHA_PRIVATE_KEY: NkxmNlJqUWdBQUFBQUloaWpLdnlOYm9faFdJZUpKa2dxTEZmVEFScg==
  RECAPTCHA_PUBLIC_KEY: NkxmNlJqUWdBQUFBQUxJWDlmT0t1d1BFRmJTdU03OWVNemtuQ3Ntcg==
  REDIS_PREFIX: d3MwMTIz
  REDIS_SERVICE: cmVkaXM6Ly9yZWRpczo2Mzc5
  STATIC_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
kind: Secret
metadata:
  name: website0123-secret
  namespace: websites-v2
type: Opaque