apiVersion: v1
data:
  CLIENT_ID: NDAw
  API_LAYWAY: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  DEBUG: dHJ1ZQ==
  DEFAULT_FROM_EMAIL: bm9yZXBseUBwaW5vZ3kud2Vic2l0ZQ==
  DJANGO_EXTRA_APPS: cGlub2d5X2F2YWlsYWJsZV9wZXRzLHBpbm9neV9sb2NhdGlvbnMscGlub2d5X2NhcmRjb25uZWN0X2lmcmFtZV90b2tlbml6ZXI=
  DJANGO_SETTINGS_MODULE: cGlub2d5X2FwcC5zZXR0aW5ncy5wcm9kdWN0aW9u
  EMAIL_HOST: c210cC5zZW5kZ3JpZC5jb20=
  EMAIL_HOST_PASSWORD: U0cuZmtZZ1NrUUxRTDZUU3JrR1lxNV82US5WYTVIS2syQWxNWUpuVzRQcnVQZUNzNXJrMGRRVWFjUFRfa29LSXlPM3hN
  EMAIL_HOST_USER: YXBpa2V5
  EMAIL_PORT: NTg5
  ENVIRONMENT: UFJPRFVDVElPTg==
  HOST_LIST: Ilt3ZWJzaXRlMDEzNi5waW5vZ3kuZGV2XSIK
  IMAGE_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
  PINOGY_ACCESS_KEY: aGJkQks3M3ZnY0ZXSzdmblhKc20=
  PINOGY_API_HOST: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  PINOGY_API_PASS: MjAyMy0wNy0wNTEwOjExOjEzNg==
  PINOGY_SECRET_KEY: cnBUSEdQN1pOZ1RQZzgzaHRzN3Y=
  POSTGRES_DB: d3MwMTM2
  POSTGRES_HOST: MTAuNzMuMC4zOQ==
  POSTGRES_PASSWORD: OTViYmQ1Zjg3OTE0NjFmYjBiOGZmYTE3ZjkzODI2MWU0YmFjZTFjZTk5MDhlMTNmYjYyYWM1OTlkNGVmNjlhMw==
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: d3NtYXN0ZXIwMTM2
  RECAPTCHA_PRIVATE_KEY: NkxlTlJqUWdBQUFBQUpxZnFlVGRKSTloSi1lSXhxQk41NXc2WmM0TA==
  RECAPTCHA_PUBLIC_KEY: NkxlTlJqUWdBQUFBQUZoQm5DdkNpdW5qZFdGZWFuM09tUElKbEUxVA==
  REDIS_PREFIX: d3MwMTM2
  REDIS_SERVICE: cmVkaXM6Ly9yZWRpczo2Mzc5
  STATIC_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
kind: Secret
metadata:
  name: website0136-secret
  namespace: websites-v2
type: Opaque