apiVersion: v1
data:
  HOST_LIST: Ilt3ZWJzaXRlMDE0Mi5waW5vZ3kuZGV2XSI=
  POSTGRES_DB: d3MwMTQy
  POSTGRES_USER: d3NtYXN0ZXIwMTQy
  REDIS_PREFIX: d3MwMTQy
  CLIENT_ID: MjIy
  INTEGRATION_ID: MzA=
  PINOGY_ACCESS_KEY: V3ZGcHcybjhmRGJ2Q2dYckJSNXo=
  PINOGY_API_PASS: MjAyMS0xMi0wMzEzOjQ2OjMzNg==
  PINOGY_SECRET_KEY: U2QyVFRDQ2o2N1dWZHRIcE0zZzI=
  POSTGRES_PASSWORD: ODNlZmY2YmY5MTNlZGVhMzBlMzEzMWNmNjFmZTI1YTZhNTc3MmNjZmM3NWZlZDQ3MWNiZWQzZTc5OWFmZTliZg==
  RECAPTCHA_PRIVATE_KEY: NkxlTlJqUWdBQUFBQUpxZnFlVGRKSTloSi1lSXhxQk41NXc2WmM0TA==
  RECAPTCHA_PUBLIC_KEY: NkxlTlJqUWdBQUFBQUZoQm5DdkNpdW5qZFdGZWFuM09tUElKbEUxVA==
  API_LAYWAY: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  DEBUG: ""
  DEFAULT_FROM_EMAIL: bm9yZXBseUBwaW5vZ3kud2Vic2l0ZQ==
  DJANGO_EXTRA_APPS: cGlub2d5X2F2YWlsYWJsZV9wZXRzLHBpbm9neV9sb2NhdGlvbnMscGlub2d5X2NhcmRjb25uZWN0X2lmcmFtZV90b2tlbml6ZXI=
  DJANGO_SETTINGS_MODULE: cGlub2d5X2FwcC5zZXR0aW5ncy5wcm9kdWN0aW9u
  EMAIL_HOST: c210cC5zZW5kZ3JpZC5jb20=
  EMAIL_HOST_PASSWORD: U0cuZmtZZ1NrUUxRTDZUU3JrR1lxNV82US5WYTVIS2syQWxNWUpuVzRQcnVQZUNzNXJrMGRRVWFjUFRfa29LSXlPM3hN
  EMAIL_HOST_USER: YXBpa2V5
  EMAIL_PORT: NTg5
  ENVIRONMENT: UFJPRFVDVElPTg==
  IMAGE_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
  PINOGY_API_HOST: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  POSTGRES_HOST: MTAuNzMuMC4zOQ==
  POSTGRES_PORT: NTQzMg==
  REDIS_SERVICE: cmVkaXM6Ly9yZWRpczo2Mzc5
  STATIC_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
kind: Secret
metadata:
  name: website0142-secret
  namespace: websites-v2
type: Opaque