apiVersion: v1
data:
  API_LAYWAY: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  CLIENT_ID: MzYz
  DEBUG: ""
  DEFAULT_FROM_EMAIL: bm9yZXBseUBwaW5vZ3kud2Vic2l0ZQ==
  DJANGO_EXTRA_APPS: cGlub2d5X2F2YWlsYWJsZV9wZXRzLHBpbm9neV9sb2NhdGlvbnMscGlub2d5X2NhcmRjb25uZWN0X2lmcmFtZV90b2tlbml6ZXI=
  DJANGO_SETTINGS_MODULE: cGlub2d5X2FwcC5zZXR0aW5ncy5wcm9kdWN0aW9u
  EMAIL_HOST: c210cC5zZW5kZ3JpZC5jb20=
  EMAIL_HOST_PASSWORD: U0cuZmtZZ1NrUUxRTDZUU3JrR1lxNV82US5WYTVIS2syQWxNWUpuVzRQcnVQZUNzNXJrMGRRVWFjUFRfa29LSXlPM3hN
  EMAIL_HOST_USER: YXBpa2V5
  EMAIL_PORT: NTg5
  ENVIRONMENT: UFJPRFVDVElPTg==
  HOST_LIST: Ilt3ZWJzaXRlMDEyNS5waW5vZ3kuZGV2XSIK
  IMAGE_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
  INTEGRATION_ID: NDk=
  PINOGY_ACCESS_KEY: Rkszc3doY0hSRnZiUHc4WmZHWGg=
  PINOGY_API_HOST: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  PINOGY_API_PASS: MjAyMi0xMC0yNzE2OjMzOjE3NQ==
  PINOGY_SECRET_KEY: cUtRQ2I3RzdOUjVqOVZSeDJqSjI=
  POSTGRES_DB: d3MwMTI1
  POSTGRES_HOST: MTAuNzMuMC4zOQ==
  POSTGRES_PASSWORD: MDdhNGU3YmZiZWU0M2MwNWM1OTEyNTBmMGQwNzU5Yzg1MDg5NTNjMTQ4YmMzM2JiMjFmODk1NDBmODRhZmJkNA==
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: d3NtYXN0ZXIwMTI1
  RECAPTCHA_PRIVATE_KEY: NkxmRjhSc1RBQUFBQU5rSUdrd3N2TXFNVjVBY3RrWG4xTkZmdnJnWA==
  RECAPTCHA_PUBLIC_KEY: NkxmRjhSc1RBQUFBQUtyV1dncmFuWTU4a2NIWXF2N2tGOXN5UktvRw==
  REDIS_PREFIX: d3MwMTI1
  REDIS_SERVICE: cmVkaXM6Ly9yZWRpczo2Mzc5
  STATIC_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
kind: Secret
metadata:
  labels:
    domain: allpetsconsidered.com
  name: website0125-secret
  namespace: websites-v2
type: Opaque