apiVersion: v1
data:
  CLIENT_ID: MTA3
  HOST_LIST: Ilt3ZWJzaXRlMDE0OC5waW5vZ3kuZGV2XSI=
  INTEGRATION_ID: MA==
  PINOGY_ACCESS_KEY: d3h6UEw1N3hMNzREYk1mNjdjczQ=
  PINOGY_API_PASS: MjAyMy0xMC0zMTE2OjIxOjI4MTc5
  PINOGY_SECRET_KEY: Y3ZUbVhaWG1Ua2Q1a0Q3aHFLN0M=
  POSTGRES_DB: d3MwMTQ4
  POSTGRES_PASSWORD: MTg2NmNiYjYwN2EzYmVhN2Q0YmYxMGQzOWQyN2RkMDJlMzY0NzNjZTJjYmIwNTVhOTZhNzQ3MGZkYTc2ZDY4OQ==
  POSTGRES_USER: d3NtYXN0ZXIwMTQ4
  RECAPTCHA_PRIVATE_KEY: NkxjOW9mc2lBQUFBQUdLb0J1QlJ5c3lSVEFUNlQ1VkdWVDFXYi1KTA==
  RECAPTCHA_PUBLIC_KEY: NkxjOW9mc2lBQUFBQVBHbnEwNnBHTHhZaTI3NENPV3pfNVdLR3FZbg==
  REDIS_PREFIX: d3MwMTQ4
  API_LAYWAY: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  BASE_TYPE: R0NQ
  DEBUG: ""
  DEFAULT_FROM_EMAIL: bm9yZXBseUBwaW5vZ3kud2Vic2l0ZQ==
  DJANGO_EXTRA_APPS: cGlub2d5X2F2YWlsYWJsZV9wZXRzLHBpbm9neV9sb2NhdGlvbnMscGlub2d5X2NhcmRjb25uZWN0X2lmcmFtZV90b2tlbml6ZXI=
  DJANGO_SETTINGS_MODULE: cGlub2d5X2FwcC5zZXR0aW5ncy5wcm9kdWN0aW9u
  EMAIL_HOST: c210cC5zZW5kZ3JpZC5jb20=
  EMAIL_HOST_PASSWORD: U0cuZmtZZ1NrUUxRTDZUU3JrR1lxNV82US5WYTVIS2syQWxNWUpuVzRQcnVQZUNzNXJrMGRRVWFjUFRfa29LSXlPM3hN
  EMAIL_HOST_USER: YXBpa2V5
  EMAIL_PORT: NTg5
  ENVIRONMENT: UFJPRFVDVElPTg==
  IMAGE_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
  PINOGY_API_HOST: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  POSTGRES_HOST: MTAuNzMuMC4zOQ==
  POSTGRES_PORT: NTQzMg==
  REDIS_SERVICE: cmVkaXM6Ly9yZWRpczo2Mzc5
  STATIC_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
kind: Secret
metadata:
  name: website0148-secret
  namespace: websites-v2
type: Opaque