apiVersion: v1
data:
  HOST_LIST: Ilt3ZWJzaXRlMDE0NC5waW5vZ3kuZGV2XSI=
  POSTGRES_DB: d3MwMTQ0
  POSTGRES_USER: d3NtYXN0ZXIwMTQ0
  REDIS_PREFIX: d3MwMTQ0
  CLIENT_ID: NDk1
  INTEGRATION_ID: Nw==
  PINOGY_ACCESS_KEY: UjNXUlJ0cmpIMk1TcGhQSnNiUVc=
  PINOGY_API_PASS: MjAyMi0wMS0wMzE3OjQ2OjQ0Ng==
  PINOGY_SECRET_KEY: Rk1tTjlCd2g3VG52cWhUZE5yNlE=
  POSTGRES_PASSWORD: YTBkOWVlNjEyOTdhNjFlMDM4ZWI3ZWZmNjBjMWJkNmY2Yjc3YTFmMWU4Njg5ZmEzZDBhMDE3Y2UxNmY3ZjMzNw==
  RECAPTCHA_PRIVATE_KEY: NkxmRjhSc1RBQUFBQU5rSUdrd3N2TXFNVjVBY3RrWG4xTkZmdnJnWA==
  RECAPTCHA_PUBLIC_KEY: NkxmRjhSc1RBQUFBQUtyV1dncmFuWTU4a2NIWXF2N2tGOXN5UktvRw==
  API_LAYWAY: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  DEBUG: ""
  DEFAULT_FROM_EMAIL: bm9yZXBseUBwaW5vZ3kud2Vic2l0ZQ==
  DJANGO_EXTRA_APPS: cGlub2d5X2F2YWlsYWJsZV9wZXRzLHBpbm9neV9sb2NhdGlvbnMscGlub2d5X2NhcmRjb25uZWN0X2lmcmFtZV90b2tlbml6ZXI=
  DJANGO_SETTINGS_MODULE: cGlub2d5X2FwcC5zZXR0aW5ncy5wcm9kdWN0aW9u
  EMAIL_HOST: c210cC5zZW5kZ3JpZC5jb20=
  EMAIL_HOST_PASSWORD: U0cuZmtZZ1NrUUxRTDZUU3JrR1lxNV82US5WYTVIS2syQWxNWUpuVzRQcnVQZUNzNXJrMGRRVWFjUFRfa29LSXlPM3hN
  EMAIL_HOST_USER: YXBpa2V5
  EMAIL_PORT: NTg5
  ENVIRONMENT: UFJPRFVDVElPTg==
  IMAGE_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
  PINOGY_API_HOST: aHR0cHM6Ly9hcGktY29yZXBvc3dlYi12MS5waW5vZ3kuY29t
  POSTGRES_HOST: MTAuNzMuMC4zOQ==
  POSTGRES_PORT: NTQzMg==
  REDIS_SERVICE: cmVkaXM6Ly9yZWRpczo2Mzc5
  STATIC_PATH: L3N0YXRpYy1maWxlcy9pbWFnZXMv
kind: Secret
metadata:
  name: website0144-secret
  namespace: websites-v2
type: Opaque