# Generated by Django 3.1.14 on 2022-08-30 06:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('custom_design', '0004_auto_20220830_1208'),
        ('common_plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpluginmodel',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.CreateModel(
            name='HeaderPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.cmsplugin')),
                ('glossary', models.JSONField(blank=True, default=dict)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_logo', to='custom_design.themeimages')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
