# Generated by Django 3.1.14 on 2022-09-03 06:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('common_plugins', '0002_auto_20220830_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpluginmodel',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Selected Banner Image', null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.CreateModel(
            name='BannerImageModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.cmsplugin')),
                ('glossary', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, default=None, help_text='Banner Image Choices', null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])])),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_plugins.bannerpluginmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
