# Generated by Django 3.1.14 on 2022-09-03 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('common_plugins', '0003_auto_20220903_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpluginmodel',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.DeleteModel(
            name='BannerImageModel',
        ),
    ]
