# Generated by Django 3.1.14 on 2023-04-19 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0007_sliderpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpluginmodel',
            name='mobimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
    ]
