# Generated by Django 3.1.14 on 2023-04-24 07:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('common_plugins', '0008_bannerpluginmodel_mobimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.cmsplugin')),
                ('glossary', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])])),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
