# Generated by Django 3.1.14 on 2023-04-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0008_bannerpluginmodel_mobimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoblockfirstpluginmodel',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='background'),
        ),
    ]
