# Generated by Django 3.1.14 on 2023-04-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0009_gallerypluginmodel'),
        ('common_plugins', '0009_infoblockfirstpluginmodel_video'),
    ]

    operations = [
    ]
