# Generated by Django 3.2.19 on 2023-07-07 13:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('common_plugins', '0012_contactusinfopluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCarouselModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='common_plugins_cardcarouselmodel', serialize=False, to='cms.cmsplugin')),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('slides_to_scroll', models.PositiveIntegerField(default=1, help_text='This variable allows you to set the  amount of items to scroll at a time.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='slides to scroll')),
                ('items', models.PositiveSmallIntegerField(default=1, help_text='This variable allows you to set the maximum amount of items displayed at a time with the widest browser width.', verbose_name='items')),
                ('items_desktop', models.PositiveSmallIntegerField(default=1, help_text='The number of items to display when the client browser is at "desktop" width.', verbose_name='items for desktop')),
                ('items_tablet', models.PositiveSmallIntegerField(default=1, help_text='The number of items to display when the client browser is at "tablet" width.', verbose_name='items for tablet')),
                ('items_mobile', models.PositiveSmallIntegerField(default=1, help_text='The number of items to display when the client browser is at "mobile" width.', verbose_name='items for mobile')),
                ('card_background', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
