# Generated by Django 3.2.19 on 2023-10-23 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0013_cardcarouselmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoblockfirstpluginmodel',
            name='bg_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
    ]
