# Generated by Django 3.2.19 on 2023-11-30 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0014_infoblockfirstpluginmodel_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoblockfirstpluginmodel',
            name='mobimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
    ]
