# Generated by Django 3.2.19 on 2023-12-18 11:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0015_infoblockfirstpluginmodel_mobimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpluginmodel',
            name='button_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
