# Generated by Django 3.2.19 on 2024-01-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('common_plugins', '0016_bannerpluginmodel_button_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='common_plugins_popuppluginmodel', serialize=False, to='cms.cmsplugin')),
                ('btn_text', models.CharField(blank=True, max_length=50, null=True)),
                ('popuptitle', models.CharField(blank=True, max_length=40, null=True)),
                ('popuptitlecolor', models.CharField(blank=True, max_length=40, null=True)),
                ('popupmessage', models.CharField(blank=True, max_length=40, null=True)),
                ('popupmessagecolor', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
