# Generated by Django 3.2.19 on 2024-01-10 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0017_auto_20240105_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoblockfirstpluginmodel',
            name='image_left',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='infoblockfirstpluginmodel',
            name='image_right',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
    ]
