# Generated by Django 3.2.19 on 2024-01-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0018_auto_20240110_1416'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='infoblockfirstpluginmodel',
        #     name='button_data',
        #     field=models.JSONField(default=None),
        # ),
    ]
