# Generated by Django 3.2.19 on 2024-01-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0019_auto_20240117_1625'),
        ('common_plugins', '0019_auto_20240117_1627'),
    ]

    operations = [
    ]
