# Generated by Django 3.2.19 on 2024-03-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0020_merge_0019_auto_20240117_1625_0019_auto_20240117_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpluginmodel',
            name='button_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='infoblockfirstpluginmodel',
            name='button_data',
            field=models.JSONField(default=dict),
        ),
    ]
