# Generated by Django 3.2.19 on 2024-04-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0023_instagramdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramdata',
            name='post_id',
            field=models.CharField(max_length=255),
        ),
    ]
