# Generated by Django 3.2.19 on 2024-05-01 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0024_alter_instagramdata_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribepluginmodel',
            name='newsletter_bg_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='subscribepluginmodel',
            name='newsletter_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='subscribepluginmodel',
            name='newsletter_left_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='subscribepluginmodel',
            name='newsletter_right_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
    ]
