# Generated by Django 3.2.19 on 2024-05-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0025_auto_20240501_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpluginmodel',
            name='external_quick_links',
            field=models.JSONField(default=dict),
        ),
    ]
