# Generated by Django 3.2.19 on 2024-05-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0026_footerpluginmodel_external_quick_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerpluginmodel',
            name='Header_external_quick_links',
            field=models.JSONField(default=dict),
        ),
    ]
