# Generated by Django 3.2.19 on 2024-06-27 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0027_headerpluginmodel_header_external_quick_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribepluginmodel',
            name='newsletter_bg_image',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='subscribepluginmodel',
            name='newsletter_image',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='subscribepluginmodel',
            name='newsletter_left_image',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='subscribepluginmodel',
            name='newsletter_right_image',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='background', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
    ]
