# Generated by Django 3.2.19 on 2024-07-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('common_plugins', '0029_alter_headerpluginmodel_header_external_quick_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='External_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exernal_target', models.CharField(blank=True, choices=[('_self', 'Same Window'), ('_blank', 'New Window')], default='_self', max_length=28, null=True)),
                ('exernal_type', models.CharField(blank=True, choices=[('internal', 'Internal link'), ('external', 'External link')], default='_self', max_length=28, null=True)),
                ('ext_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
        ),
    ]
