# Generated by Django 3.2.19 on 2024-07-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('common_plugins', '0030_external_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_links',
            name='ext_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_link', to='cms.page'),
        ),
    ]
