# Generated by Django 3.2.19 on 2024-09-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0032_external_links_internal_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerpluginmodel',
            name='Header_external_quick_links',
        ),
    ]
