# Generated by Django 3.2.19 on 2024-09-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('common_plugins', '0033_remove_headerpluginmodel_header_external_quick_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='external_links',
            name='childId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='external_links',
            name='parentId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='external_links',
            name='ext_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_link', to='cms.page'),
        ),
    ]
