# Generated by Django 3.2.19 on 2024-09-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('common_plugins', '0033_remove_headerpluginmodel_header_external_quick_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabItemCompoPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='common_plugins_tabitemcompopluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TabsCompoPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='common_plugins_tabscompopluginmodel', serialize=False, to='cms.cmsplugin')),
                ('style', models.CharField(choices=[('tabs', 'Tabs'), ('pills', 'Pills')], default='tabs', max_length=255, verbose_name='Type')),
                ('alignment', models.CharField(choices=[('', '-----'), ('fill', 'Fill'), ('justified', 'Justified'), ('justify center', 'Justify center'), ('justify end', 'Justify end'), ('column', 'Column')], default='', max_length=255, verbose_name='Alignment')),
                ('animation', models.CharField(choices=[('', '-----'), ('fade', 'Fade')], default='', max_length=255, verbose_name='Animation')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
