# Generated by Django 3.2.19 on 2024-09-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0034_auto_20240918_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='external_links',
            name='exernal_link_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
