# Generated by Django 3.2.19 on 2024-09-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('common_plugins', '0034_tabitemcompopluginmodel_tabscompopluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnSubscribePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.cmsplugin')),
                ('glossary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='tabscompopluginmodel',
            name='alignment',
            field=models.CharField(blank=True, choices=[('', '-----'), ('nav-fill', 'Fill'), ('nav-justified', 'Justified'), ('justify-content-center', 'Justify center'), ('justify-content-end', 'Justify end'), ('flex-column', 'Column')], default='', max_length=255, verbose_name='Alignment'),
        ),
        migrations.AlterField(
            model_name='tabscompopluginmodel',
            name='animation',
            field=models.CharField(blank=True, choices=[('', '-----'), ('fade', 'Fade')], default='', max_length=255, verbose_name='Animation'),
        ),
        migrations.AlterField(
            model_name='tabscompopluginmodel',
            name='style',
            field=models.CharField(blank=True, choices=[('tabs', 'Tabs'), ('pills', 'Pills')], default='tabs', max_length=255, verbose_name='Type'),
        ),
    ]
