# Generated by Django 3.2.19 on 2024-09-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0036_external_links_exernal_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_links',
            name='parentId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
