# Generated by Django 3.2.19 on 2024-09-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0034_tabitemcompopluginmodel_tabscompopluginmodel'),
        ('common_plugins', '0037_alter_external_links_parentid'),
    ]

    operations = [
    ]
