# Generated by Django 3.2.19 on 2024-09-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0038_merge_20240924_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabscompopluginmodel',
            name='alignment',
            field=models.CharField(blank=True, choices=[('', '-----'), ('nav-fill', 'Fill'), ('nav-justified', 'Justified'), ('justify-content-center', 'Justify center'), ('justify-content-end', 'Justify end'), ('flex-column', 'Column')], default='', max_length=255, verbose_name='Alignment'),
        ),
        migrations.AlterField(
            model_name='tabscompopluginmodel',
            name='animation',
            field=models.CharField(blank=True, choices=[('', '-----'), ('fade', 'Fade')], default='', max_length=255, verbose_name='Animation'),
        ),
        migrations.AlterField(
            model_name='tabscompopluginmodel',
            name='style',
            field=models.CharField(blank=True, choices=[('tabs', 'Tabs'), ('pills', 'Pills')], default='tabs', max_length=255, verbose_name='Type'),
        ),
    ]
