# Generated by Django 3.2.19 on 2024-09-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('common_plugins', '0040_external_links_draftid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_links',
            name='ext_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_link', to='cms.page'),
        ),
    ]
