# Generated by Django 3.2.19 on 2024-09-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_plugins', '0035_auto_20240930_1435'),
        ('common_plugins', '0041_alter_external_links_ext_page'),
    ]

    operations = [
    ]
