# Generated by Django 2.1.1 on 2020-03-13 11:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinogy_testimonials', '0002_auto_20180402_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, default=None, help_text='Share a photo of your pet. (JPG, PNG accepted up to 2MBs)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='your pet photo'),
        ),
        migrations.AlterField(
            model_name='testimonialcarouselpluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='testimonialcarouselpluginmodel',
            name='max_testimonials',
            field=models.PositiveIntegerField(default=5, help_text='How many should be shown (up to 100)?', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='max. testimonials'),
        ),
        migrations.AlterField(
            model_name='testimonialformpluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='testimonialquotespluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='testimonialquotespluginmodel',
            name='max_testimonials',
            field=models.PositiveIntegerField(default=5, help_text='How many should be shown (up to 100)?', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='max. testimonials'),
        ),
        migrations.AlterField(
            model_name='testimonialtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pinogy_testimonials.Testimonial'),
        ),
    ]
