# Generated by Django 2.1.1 on 2020-04-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinogy_testimonials', '0003_auto_20200313_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
