# Generated by Django 2.1.1 on 2022-04-07 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('pinogy_testimonials', '0007_auto_20220331_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialListsPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pinogy_testimonials_testimoniallistsplugin', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='testimonialcarouselpluginmodel',
            name='available_template',
            field=models.CharField(blank=True, choices=[('testimonials_new/plugins/testimonial_carousel/testimonial_carousel.html', 'Default'), ('testimonials_new/plugins/testimonial_carousel/images_with_text_right.html', 'Image with text in right'), ('testimonials_new/plugins/testimonial_carousel/image_text_right_curve_corner.html', 'Image with text in right and curve corner')], default='testimonials_new/plugins/testimonial_carousel/testimonial_carousel.html', max_length=256, null=True, verbose_name='Available Template'),
        ),
        migrations.AddField(
            model_name='testimoniallistsplugin',
            name='available_template',
            field=models.CharField(choices=[('testimonials_new/plugins/testimonial_carousel/image_text_right_curve_corner.html', 'Curve Corner Card')], default='testimonials_new/plugins/testimonial_carousel/image_text_right_curve_corner.html', max_length=256, verbose_name='Available Template'),
        ),
    ]
