# Generated by Django 2.1.1 on 2022-04-13 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('pinogy_testimonials', '0008_auto_20220407_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialListsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pinogy_testimonials_testimoniallistspluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('available_template', models.CharField(choices=[('testimonials_new/plugins/testimonial_carousel/image_text_right_curve_corner.html', 'Curve Corner Card')], default='testimonials_new/plugins/testimonial_carousel/image_text_right_curve_corner.html', max_length=256, verbose_name='Available Template')),
                ('displayed_count', models.PositiveIntegerField(default=0, help_text='How many testimonials displayed in List? (0 for all)', verbose_name='displayed count')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='testimoniallistsplugin',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='TestimonialListsPlugin',
        ),
    ]
