# Generated by Django 2.1.1 on 2022-10-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinogy_testimonials', '0010_auto_20220421_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('-creation_date',), 'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
        migrations.AlterField(
            model_name='testimoniallistspluginmodel',
            name='available_template',
            field=models.CharField(choices=[('testimonials_new/plugins/testimonial_list/image_with_curve_corner.html', 'Curve Corner Card'), ('testimonials_new/plugins/testimonial_list/image_with_text_side.html', 'Image with Text at Side')], default='testimonials_new/plugins/testimonial_list/image_with_curve_corner.html', max_length=256, verbose_name='Available Template'),
        ),
    ]
