# Generated by Django 3.1.14 on 2023-06-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinogy_testimonials', '0011_auto_20221031_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(help_text='Place name same listed on google buisness.', max_length=256)),
                ('google_place_id', models.CharField(help_text='Place ID of location as per the google buisness.', max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=256)),
                ('author_url', models.URLField()),
                ('profile_photo_url', models.URLField()),
                ('rating', models.FloatField()),
                ('text', models.TextField(help_text='Store Reviews description.')),
            ],
        ),
    ]
