# Generated by Django 3.1.14 on 2023-06-08 12:31

from django.db import migrations, models
import django.db.models.deletion
import pinogy_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('pinogy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMapModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pinogy_app_sitemapmodel', serialize=False, to='cms.cmsplugin')),
                ('document', models.FileField(blank=True, null=True, upload_to=pinogy_app.models.get_file_path, validators=[pinogy_app.models.validate_file_ext])),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
