# Generated by Django 3.1.14 on 2023-06-12 12:46

from django.db import migrations, models
import pinogy_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pinogy_app', '0002_sitemapmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemapmodel',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=pinogy_app.models.get_file_path, validators=[pinogy_app.models.validate_file_ext]),
        ),
    ]

